# Generated by Django 5.2.6 on 2026-02-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_delete_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='total_amount',
            new_name='fee',
        ),
    ]
