# Generated by Django 5.2.6 on 2026-01-18 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='password',
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
