# Generated by Django 5.2.6 on 2026-01-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userrole_email_remove_userrole_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='available_timings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
