# Generated by Django 6.0.1 on 2026-02-04 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userrole_available_timings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_status', models.CharField(blank=True, help_text='Any diagnosed disease', max_length=255, null=True)),
                ('blood_pressure', models.CharField(help_text='e.g. 120/80', max_length=20)),
                ('heart_rate', models.PositiveIntegerField(help_text='Beats per minute')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('report_file', models.FileField(blank=True, help_text='Doctor uploaded report (PDF, image)', null=True, upload_to='health_reports/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
